import type { Metadata } from "next";
import Link from 'next/link'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarNav from "@/components/SidebarNav";
import { Toaster } from "@/components/ui/toaster";
import { SocketProvider } from "../context/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <SocketProvider>
        <SidebarProvider>
        <div className="flex h-screen w-full">
        {/* Sidebar */}
        <SidebarNav />
        {children}
        <Toaster />
        </div>
        </SidebarProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
